# Sharing dependency versions between projects
# https://docs.gradle.org/current/userguide/platforms.html

[versions]
buildTools = "30.0.3"
compileSdk = "31"
minSdk = "23"
targetSdk = "31"

# Library versions
accompanist = "0.18.0"
androidx-compose = "1.0.4"
androidx-lifecycle = "2.4.0"
androidx-material = "1.4.0"
androidx-navigation = "2.4.0-beta01"
androidx-room = "2.3.0"
androidx-test = "1.4.0"
coroutines = "1.5.2"
detekt = "1.18.1"
hilt = "2.40"
kotlin = "1.5.31"

[libraries]
accompanist-insets = { module = "com.google.accompanist:accompanist-insets", version.ref = "accompanist" }
accompanist-pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanist" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version = "1.4.0" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.3.1" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "androidx-compose" }
androidx-compose-layout = { module = "androidx.compose.foundation:foundation-layout", version.ref = "androidx-compose" }
androidx-compose-material = { module = "androidx.compose.material:material", version.ref = "androidx-compose" }
androidx-compose-materialIconsExtended = { module = "androidx.compose.material:material-icons-extended", version.ref = "androidx-compose" }
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "androidx-compose" }
androidx-compose-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "androidx-compose" }
androidx-compose-test = { module = "androidx.compose.test:test-core", version.ref = "androidx-compose" }
androidx-compose-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidx-compose" }
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "androidx-compose" }
androidx-compose-uiTest = { module = "androidx.compose.ui:ui-test", version.ref = "androidx-compose" }
androidx-constraintlayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version = "1.0.0-beta02" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version = "1.7.0" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version = "1.0.0-alpha02" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-material = { module = "com.google.android.material:material", version.ref = "androidx-material" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }
androidx-navigation-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidx-navigation" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "androidx-navigation" }
androidx-palette = { module = "androidx.palette:palette", version = "1.0.0" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "androidx-room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidx-room" }
androidx-startup = { module = "androidx.startup:startup-runtime", version = "1.1.0" }
androidx-test-core = { module = "androidx.test:core", version.ref = "androidx-test" }
androidx-test-espresso-core = { module = "androidx.test.espresso:espresso-core", version = "3.4.0" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit-ktx", version = "1.1.3" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidx-test" }
coil-compose = { module = "io.coil-kt:coil-compose", version = "1.3.0" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
detekt = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics-ktx", version = "19.0.2" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics-ktx", version = "18.2.3" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version = "1.0.0-alpha03" }
junit = { module = "junit:junit", version = "4.13.2" }
kotlin-extensions = { module = "org.jetbrains.kotlin:kotlin-android-extensions", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version = "2.7" }
timber = { module = "com.jakewharton.timber:timber", version = "5.0.1" }

# plugins
plugin-android = { module = "com.android.tools.build:gradle", version = "7.0.3" }
plugin-androidx-navigation-safeargs = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "androidx-navigation" }
plugin-detekt = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
plugin-firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics-gradle", version = "2.7.1" }
plugin-hilt = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }
plugin-jdkdesugar = { module = "com.android.tools:desugar_jdk_libs", version = "1.1.5" }
plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
plugin-versionsgradle = { module = "com.github.ben-manes:gradle-versions-plugin", version = "0.39.0" }
plugin-spotless = { module = "com.diffplug.spotless:spotless-plugin-gradle", version = "5.15.0" }
